### PR TITLE
test slab pmem freeq

### PR DESCRIPTION
**Pull request by karpiop**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/50)

### CODE REVIEW

**Comment by kasiawasiuta** [comment]
@pmem-bot-ae 
test this please

**Review by kasiawasiuta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/50)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karpiop)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1233 at r1](https://reviewable.io/reviews/pmem/pelikan/50#-Llex3Ed8mgRx5iFvDCA:-Llex3Ed8mgRx5iFvDCB:bv0l960) ([raw file](https://github.com/pmem/pelikan/blob/663abdfd221c06c8a0bb810b87bb54260414e06f/test/storage/slab_pmem/check_slab_pmem.c#L1233)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     ck_assert_msg(slabclass[id].nfree_itemq == 1, "Slabclass %d has %d item(s) in freeq", id ,slabclass[id].nfree_itemq);
> 
>     it = slabclass[id].free_itemq.slh_first;
> 
>     ck_assert_msg(it->in_freeq == 1, "Item not flagged as in freeq");
> ```
</details>

Consider removing this whitelines. Apart from that :lgtm:

**Review by karpiop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/50)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1233 at r1](https://reviewable.io/reviews/pmem/pelikan/50#-Llex3Ed8mgRx5iFvDCA:-LlfFU702d7GUk_k--Se:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/663abdfd221c06c8a0bb810b87bb54260414e06f/test/storage/slab_pmem/check_slab_pmem.c#L1233)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
>     ck_assert_msg(slabclass[id].nfree_itemq == 1, "Slabclass %d has %d item(s) in freeq", id ,slabclass[id].nfree_itemq);
> 
>     it = slabclass[id].free_itemq.slh_first;
> 
>     ck_assert_msg(it->in_freeq == 1, "Item not flagged as in freeq");
> ```
Consider removing this whitelines. Apart from that :lgtm: 
</blockquote></details>

Done.

**Review by TomekIdczak97 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/50#-:-Llq2ANZ3-W7LaCCxKx3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta)

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/50)* status: all files reviewed, 5 unresolved discussions (waiting on @karpiop and @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1229 at r2](https://reviewable.io/reviews/pmem/pelikan/50#-LmdHP5s1riUBzT-krov:-LmdHP5s1riUBzT-krow:bkvbpyo) ([raw file](https://github.com/pmem/pelikan/blob/3d03680b30fc8234d6142488e2ed47e99e16c49f/test/storage/slab_pmem/check_slab_pmem.c#L1229)):*
> ```
> d
> ```
u
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1229 at r2](https://reviewable.io/reviews/pmem/pelikan/50#-LmdHQhd5CICIWsFJCsi:-LmdHQhe517-70nU9L7z:bkvbpyo) ([raw file](https://github.com/pmem/pelikan/blob/3d03680b30fc8234d6142488e2ed47e99e16c49f/test/storage/slab_pmem/check_slab_pmem.c#L1229)):*
> ```
> d
> ```
u
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1229 at r2](https://reviewable.io/reviews/pmem/pelikan/50#-LmdV_Q4AYrB5IqTtHCp:-LmdV_Q4AYrB5IqTtHCq:b-eac0a9) ([raw file](https://github.com/pmem/pelikan/blob/3d03680b30fc8234d6142488e2ed47e99e16c49f/test/storage/slab_pmem/check_slab_pmem.c#L1229)):*
> ```
> id ,slabclass[id].nfree_itemq
> ```
nit:
remove space before comma and add one after
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1230 at r2](https://reviewable.io/reviews/pmem/pelikan/50#-LmdIQsi2E13h6Os6g8f:-LmdIQsi2E13h6Os6g8g:b-w8cm87) ([raw file](https://github.com/pmem/pelikan/blob/3d03680b30fc8234d6142488e2ed47e99e16c49f/test/storage/slab_pmem/check_slab_pmem.c#L1230)):*
> ```
> slabclass[id].free_itemq.slh_first;
> ```
Please don't access this directly, use appropriate interface:

SLIST_FIRST(&p->free_itemq);

p would be define as struct slabclass *p = &slabclass[id]; 

Add tonally consider usage of p variable in other places here like for nfree_itemq

**Review by karpiop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/50)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @kasiawasiuta, @michalbiesek, and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1229 at r2](https://reviewable.io/reviews/pmem/pelikan/50#-LmdHP5s1riUBzT-krov:-Lme9pAkBZ7iiWmEZb02:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3d03680b30fc8234d6142488e2ed47e99e16c49f/test/storage/slab_pmem/check_slab_pmem.c#L1229)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> d
> ```
u
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1229 at r2](https://reviewable.io/reviews/pmem/pelikan/50#-LmdHQhd5CICIWsFJCsi:-Lme9pYR7c_cutOeSdNo:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3d03680b30fc8234d6142488e2ed47e99e16c49f/test/storage/slab_pmem/check_slab_pmem.c#L1229)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> d
> ```
u
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1229 at r2](https://reviewable.io/reviews/pmem/pelikan/50#-LmdV_Q4AYrB5IqTtHCp:-Lme9sSv8tzM_TZF84z0:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3d03680b30fc8234d6142488e2ed47e99e16c49f/test/storage/slab_pmem/check_slab_pmem.c#L1229)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> id ,slabclass[id].nfree_itemq
> ```
nit:
add space after comma
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1230 at r2](https://reviewable.io/reviews/pmem/pelikan/50#-LmdIQsi2E13h6Os6g8f:-Lme9tS89xjVyk0MeQur:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3d03680b30fc8234d6142488e2ed47e99e16c49f/test/storage/slab_pmem/check_slab_pmem.c#L1230)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> slabclass[id].free_itemq.slh_first;
> ```
Please don't access this directly, use appropriate interface:

SLIST_FIRST(&p->free_itemq);

p would be define as struct slabclass *p = &slabclass[id]; 

Add tonally consider usage of p variable in other places here like for nfree_itemq

</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
:lgtm:
I assume you want add different scenarios for testing this functionality?

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/50#-:-LmhdjOA1amEdzNdsK2o:bdhc6m9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta and @TomekIdczak97)

**Pull request merged**
