### PR TITLE
slab metrics unit test: test_metrics_reserve_backfill_link

### PR DESCRIPTION
**Pull request by TomekIdczak97**
Simple slab metrics unit test for pmem: test_metrics_reserve_backfill_link

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/39)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1005 at r1](https://reviewable.io/reviews/pmem/pelikan/39#-LjpTvQ54Sg2qAaCqwPH:-LjpTvQ54Sg2qAaCqwPI:bbepvgd) ([raw file](https://github.com/pmem/pelikan/blob/46759e38390d89477b7b38fc44b1fd7c82fca8b4/test/storage/slab_pmem/check_slab_pmem.c#L1005)):*
> ```
> ····
> ```
remove whitespaces
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1006 at r1](https://reviewable.io/reviews/pmem/pelikan/39#-LjpTxrHETU26o1VzwyA:-LjpTxrHETU26o1VzwyB:b-chs3n) ([raw file](https://github.com/pmem/pelikan/blob/46759e38390d89477b7b38fc44b1fd7c82fca8b4/test/storage/slab_pmem/check_slab_pmem.c#L1006)):*
> ```
> &
> ```
(struct metric *)&

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1005 at r1](https://reviewable.io/reviews/pmem/pelikan/39#-LjpTvQ54Sg2qAaCqwPH:-LjpYH0--hoaPO7yOQ_o:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/46759e38390d89477b7b38fc44b1fd7c82fca8b4/test/storage/slab_pmem/check_slab_pmem.c#L1005)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ····
> ```
remove whitespaces
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1006 at r1](https://reviewable.io/reviews/pmem/pelikan/39#-LjpTxrHETU26o1VzwyA:-LjpYHQJ8jkrzi8EFkQT:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/46759e38390d89477b7b38fc44b1fd7c82fca8b4/test/storage/slab_pmem/check_slab_pmem.c#L1006)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> &
> ```
(struct metric *)&
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 149 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpYeqT2AIHbEHcywHm:-LjpYeqT2AIHbEHcywHn:b5qkr2v) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L149)):*
> ```
> curr++, copy++
> ```
not needed use curr[i].type in switch below and apply similar changes in whole function - therefore you could iterate only over "i"
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 152 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpYnq85-LK1n0pCIZg:-LjpYnq97CC61pRZ43Cr:bicjk1n) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L152)):*
> ```
> ck_assert_msg(copy->counter == curr->counter, "metric %s is not equal - saved: %s current: %s"
> ```
Fix asserts in this function.
Hint: call this function right after metric_reset and before test_reset(0) you should receive a segfault but you expected an assert message
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1006 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpZMZnCPnjemvR4ENw:-LjpZMZo32yNC-_fC2Bu:b-u6bo1h) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L1006)):*
> ```
> struct metric*)
> ```
nit:
struct metric *
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1009 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpYb9D5H-goWO6r4x7:-LjpYb9EBdkma_30WQLE:b-chs3n) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L1009)):*
> ```
> &
> ```
(struct metric *)&
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1009 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpYbncCo3S2NG1opLW:-LjpYbncCo3S2NG1opLX:b-chs3n) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L1009)):*
> ```
> &
> ```
(struct metric *)&

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 149 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpYeqT2AIHbEHcywHm:-LjpiTje2i3N71UGwiVM:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L149)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> curr++, copy++
> ```
not needed use curr[i].type in switch below and apply similar changes in whole function - therefore you could iterate only over "i"

</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 152 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpYnq85-LK1n0pCIZg:-LjpiTTS8_-_tfepeOps:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L152)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ck_assert_msg(copy->counter == curr->counter, "metric %s is not equal - saved: %s current: %s"
> ```
Fix asserts in this function.
Hint: call this function right after metric_reset and before test_reset(0) you should receive a segfault but you expected an assert message
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1006 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpZMZnCPnjemvR4ENw:-LjpiRV18qCFrsIrZXQH:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L1006)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct metric*)
> ```
nit:
struct metric *
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1009 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpYb9D5H-goWO6r4x7:-LjpiRxoAgnot4CHnTKr:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L1009)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> &
> ```
(struct metric *)&
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1009 at r2](https://reviewable.io/reviews/pmem/pelikan/39#-LjpYbncCo3S2NG1opLW:-LjpiSLc4H8wbKp0dk9Y:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/374f3656f39dfe61deb8198ef026aea678a7157b/test/storage/slab_pmem/check_slab_pmem.c#L1009)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> &
> ```
(struct metric *)&
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39)* status: 0 of 1 files reviewed, all discussions resolved

**Review by michalbiesek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39#-:-Ljpm4N58GLSVS8eSY2T:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by kasiawasiuta — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39)* status: all files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 153 at r3](https://reviewable.io/reviews/pmem/pelikan/39#-LjtnsX82QYLtfaZM7jQ:-LjtnsX82QYLtfaZM7jR:b4np7t6) ([raw file](https://github.com/pmem/pelikan/blob/8c2e37b70a2fe77aa6d5e71761942f0da366cfc3/test/storage/slab_pmem/check_slab_pmem.c#L153)):*
> ```C
>     char m2_buf[METRIC_BUF_LEN];
> 
>     unsigned int i;
> ```

just "unsigned" is fine

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 153 at r3](https://reviewable.io/reviews/pmem/pelikan/39#-LjtnsX82QYLtfaZM7jQ:-Ljtr5mSDE-3Blzh-Elm:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/8c2e37b70a2fe77aa6d5e71761942f0da366cfc3/test/storage/slab_pmem/check_slab_pmem.c#L153)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

just "unsigned" is fine
</blockquote></details>

Done.

**Review by kasiawasiuta — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/39#-:-LjtrJdbCCnkRJkNwk4e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
