### PR TITLE
slab metrics unit test: test_metrics_update_basic

### PR DESCRIPTION
**Pull request by TomekIdczak97**
Simple slab metrics unit test for pmem: test_metrics_update_basic

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/54)

### CODE REVIEW

**Review by karpiop — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/54)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1119 at r1](https://reviewable.io/reviews/pmem/pelikan/54#-Ll1niT5ENPi-bP2Ts1a:-Ll1niT5ENPi-bP2Ts1b:b-hvbrl4) ([raw file](https://github.com/pmem/pelikan/blob/3618b61e862213383e9482c1a244e0f22bf0da3a/test/storage/slab_pmem/check_slab_pmem.c#L1119)):*
> ```C
> #define KEY "key"
> #define OLD_VAL "old_val"
> #define NEW_VAL "new_val"
> ```

add new line

**Review by karpiop — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/54)* status: all files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/54)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karpiop)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1119 at r1](https://reviewable.io/reviews/pmem/pelikan/54#-Ll1niT5ENPi-bP2Ts1a:-Ll1y5Jr7NbDSS1TXdPw:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3618b61e862213383e9482c1a244e0f22bf0da3a/test/storage/slab_pmem/check_slab_pmem.c#L1119)):*
<details><summary><i>Previously, karpiop (Paweł Karpiński) wrote…</i></summary><blockquote>

add new line
</blockquote></details>

Done.

**Review by karpiop — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/54#-:-Ll1ymuBCuYBkKQMX5SG:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/54)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karpiop and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1176 at r3](https://reviewable.io/reviews/pmem/pelikan/54#-Lmnbm346qXB4KLF3KVc:-Lmnbm346qXB4KLF3KVd:bxbw3bw) ([raw file](https://github.com/pmem/pelikan/blob/de12fce70a33ae4b1880704431f84d54c7ed25a6/test/storage/slab_pmem/check_slab_pmem.c#L1176)):*
> ```
> #define APPEND "append"
> ```
not related with this change - if you want to fix this kind of change just open separate pr for that

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/54)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karpiop and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1176 at r3](https://reviewable.io/reviews/pmem/pelikan/54#-Lmnbm346qXB4KLF3KVc:-LmnkfRm7Kqt0tmNlPmL:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/de12fce70a33ae4b1880704431f84d54c7ed25a6/test/storage/slab_pmem/check_slab_pmem.c#L1176)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #define APPEND "append"
> ```
not related with this change - if you want to fix this kind of change just open separate pr for that
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/54#-:-LmnpFRy9BvlF88-3Gjm:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @karpiop)

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
