### PR TITLE
benchmark: extend existing slab and cuckoo benchmarks

### PR DESCRIPTION
**Pull request by pbalcer**
This patch:
 - adds automatic size adjustment for the slab micro benchmark
 - adds latency measurement
 - fixes composability of configs

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/12)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Comment by kasiawasiuta** [comment]
@nvml-bot
test this please

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/12)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @pbalcer)

___
*[benchmarks/bench_storage.c, line 32 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhERGz6EuNXaaZaOqF_:-LhERGz6EuNXaaZaOqFa:bsprwdx) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L32)):*
> ```C
>     ACTION(pct_put,         OPTION_TYPE_UINT, 10,    "% of puts")\
>     ACTION(pct_rem,         OPTION_TYPE_UINT, 10,    "% of removes")\
>     ACTION(latency,        OPTION_TYPE_BOOL, true,  "Collect latency samples")\
> ```

nit:
one more space before "OPTION_TYPE_BOOL" please
___
*[benchmarks/bench_storage.c, line 32 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhERMNlAM5ukpOtT_48:-LhERMNlAM5ukpOtT_49:b-lh9gc6) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L32)):*
> ```
> \
> ```
nit:
remove last "\\"
___
*[benchmarks/bench_storage.c, line 44 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhERQDq-I67S2u-RtUO:-LhERQDq-I67S2u-RtUP:b-khjy31) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L44)):*
> ```C
> };
> 
> const char *op_names[MAX_BENCHMARK_OPERATION] = {"get", "put", "rem"};
> ```

static
___
*[benchmarks/bench_storage.c, line 71 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEVVSB0q2E3ebUlEnn:-LhEVVSCBWd8pS_bXfWs:b-h6bp7z) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L71)):*
> ```
> size_t
> ```
nit:
if you use unsigned int you will kill compiler warnings with "implicit conversion"
___
*[benchmarks/bench_storage.c, line 100 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhERYkLDqdw69U1Q5F9:-LhERYkLDqdw69U1Q5FA:bmrzf1g) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L100)):*
> ```
> (O(b, latency))
> ```
I think you must define seperate macro for this. You acceess value using option_uint and latency variable is marked as OPTION_BOOL type
___
*[benchmarks/bench_storage.c, line 101 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhER_Hf6S8Qlq27JX1J:-LhER_Hf6S8Qlq27JX1K:bg2jy3k) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L101)):*
> ```
> enum benchmark_operation
> ```
Could this be just an "int" type (in all loops in your changes)
___
*[benchmarks/bench_storage.c, line 117 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEW8jGAIBPZaoQXhN_:-LhEW8jGAIBPZaoQXhNa:bjtetvt) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L117)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     for (enum benchmark_operation op = 0;
>             op < MAX_BENCHMARK_OPERATION; ++op) {
>         cc_free(b->latency[op].samples);
>     }
> ```
</details>

before freeing check against latency param is set to true 
___
*[benchmarks/bench_storage.c, line 220 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhESC5r1Ze2xORdUZ-m:-LhESC5r1Ze2xORdUZ-n:bjvcpdt) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L220)):*
> ```
> case MAX_BENCHMARK_OPERATION:
> ```
Replace it with "default:"
___
*[benchmarks/bench_storage.c, line 240 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhESI-WE6fekuy1UXIE:-LhESI-WE6fekuy1UXIF:bsrxb19) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L240)):*
> ```
>  O(b, nentries)
> ```
nentries - see 2 lines above it is assigned with desired value.
___
*[deps/ccommon/include/time/cc_timer.h, line 107 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhESXux8s0Equ-dmb7j:-LhESXux8s0Equ-dmb7k:b-nmldqi) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/deps/ccommon/include/time/cc_timer.h#L107)):*
> ```objc
>     double lns = duration_ns((struct duration *)lhs);
>     double rns = duration_ns((struct duration *)rhs);
> 	if (lns < rns)
> ```

Replace tabs with spaces

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/12)* status: 1 of 5 files reviewed, 12 unresolved discussions (waiting on @pbalcer)

___
*[benchmarks/bench_storage.c, line 225 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhE_uzc0o9IoyeyE7x9:-LhE_uzc0o9IoyeyE7xA:b-tp55p7) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L225)):*
> ```
> duration_stop(&latency->samples[nsample]);
> ```
Question:
Is measuring of this latency supposed to be case aware(status of GET/PUT/REM operation or only if status is ended with success CC_OK?
___
*[benchmarks/storage_slab/storage_slab.c, line 28 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEY6ZjBPEJrXkfiqpd:-LhEY6ZjBPEJrXkfiqpe:b-batx7g) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/storage_slab/storage_slab.c#L28)):*
> ```
> 64 * MiB
> ```
SLAB_MEM ?

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/12)* status: 1 of 5 files reviewed, 11 unresolved discussions (waiting on @michalbiesek)

___
*[benchmarks/bench_storage.c, line 32 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhERMNlAM5ukpOtT_48:-LhF1B1Y6ZLIRCbHkdl9:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L32)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> \
> ```
nit:
remove last "\\"
</blockquote></details>

Done.
___
*[benchmarks/bench_storage.c, line 44 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhERQDq-I67S2u-RtUO:-LhF1AkPE3yvkIXJePve:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L44)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

static
</blockquote></details>

Done.
___
*[benchmarks/bench_storage.c, line 71 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEVVSB0q2E3ebUlEnn:-LhF1DFB57x-rBTKWno_:b-w92cz0) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L71)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> size_t
> ```
nit:
if you use unsigned int you will kill compiler warnings with "implicit conversion"
</blockquote></details>

That's not necessary.
___
*[benchmarks/bench_storage.c, line 100 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhERYkLDqdw69U1Q5F9:-LhF1ChF2EygZtEnmZHN:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L100)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> (O(b, latency))
> ```
I think you must define seperate macro for this. You acceess value using option_uint and latency variable is marked as OPTION_BOOL type
</blockquote></details>

Done.
___
*[benchmarks/bench_storage.c, line 101 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhER_Hf6S8Qlq27JX1J:-LhF0Xli4NQ45Bt8FgRN:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L101)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> enum benchmark_operation
> ```
Could this be just an "int" type (in all loops in your changes)
</blockquote></details>

Done.
___
*[benchmarks/bench_storage.c, line 117 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEW8jGAIBPZaoQXhN_:-LhF0YS54CAk10dwI2WG:b8kh23q) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L117)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     for (enum benchmark_operation op = 0;
>             op < MAX_BENCHMARK_OPERATION; ++op) {
>         cc_free(b->latency[op].samples);
>     }
> ```
before freeing check against latency param is set to true 
</blockquote></details>

that's not necessary 
___
*[benchmarks/bench_storage.c, line 220 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhESC5r1Ze2xORdUZ-m:-LhF0aWM04vlNuQgHsLR:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L220)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> case MAX_BENCHMARK_OPERATION:
> ```
Replace it with "default:"
</blockquote></details>

Done.
___
*[benchmarks/bench_storage.c, line 225 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhE_uzc0o9IoyeyE7x9:-LhF0azZ6xXvp-gBk-ys:bopxbki) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L225)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> duration_stop(&latency->samples[nsample]);
> ```
Question:
Is measuring of this latency supposed to be case aware(status of GET/PUT/REM operation or only if status is ended with success CC_OK?
</blockquote></details>

I think benchmark operations shouldn't fail, and when they do - the latency numbers are meaningless anyway.
___
*[benchmarks/bench_storage.c, line 240 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhESI-WE6fekuy1UXIE:-LhF0kfGEv65-wy4y2xI:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L240)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  O(b, nentries)
> ```
nentries - see 2 lines above it is assigned with desired value.
</blockquote></details>

Done.
___
*[benchmarks/storage_slab/storage_slab.c, line 28 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEY6ZjBPEJrXkfiqpd:-LhF0lsm1-4sgLM_ZtTb:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/storage_slab/storage_slab.c#L28)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 64 * MiB
> ```
SLAB_MEM ?
</blockquote></details>

Done.
___
*[deps/ccommon/include/time/cc_timer.h, line 107 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhESXux8s0Equ-dmb7j:-LhF14Mv86q8LRCQ1sGE:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/deps/ccommon/include/time/cc_timer.h#L107)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Replace tabs with spaces
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/12)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @pbalcer)

___
*[benchmarks/bench_storage.c, line 71 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEVVSB0q2E3ebUlEnn:-LhF4w-1--qVvJG1XP-c:bwyeiqw) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L71)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

That's not necessary.
</blockquote></details>

It is not necessary, that's a fact but you will get rid of this warnings - it is low hanging fruit :)
Additionally please see that original maintainers of the code use "unsigned int" type for variable with OPTION_CARDINALITY - so consistency in this is some argument to change it
___
*[benchmarks/bench_storage.c, line 117 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEW8jGAIBPZaoQXhN_:-LhF54U491k7Sk0-0JpM:b-hks1hd) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L117)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

that's not necessary 
</blockquote></details>

Actually it is :)
Try to set latency configuration variable to false, compile the project and run ./bench_cuckoo you will hit segmentation fault.
___
*[benchmarks/bench_storage.c, line 225 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhE_uzc0o9IoyeyE7x9:-LhF7TvB9LTfNTi3AavA:b32w1t) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L225)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

I think benchmark operations shouldn't fail, and when they do - the latency numbers are meaningless anyway.
</blockquote></details>

Ok
___
*[benchmarks/bench_storage.c, line 181 at r2](https://reviewable.io/reviews/pmem/pelikan/12#-LhF8Q8yDerPaMQO89xv:-LhF8Q8yDerPaMQO89xw:b-14lld1) ([raw file](https://github.com/pmem/pelikan/blob/bcc3d55c23f31125919d5ba3a9846358c548664e/benchmarks/bench_storage.c#L181)):*
> ```
> duration_compare
> ```
nit:
Have you consider to rename this function duration_compare_asc or duration_compare_ascending - just to have clear information about order.

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/12)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[benchmarks/bench_storage.c, line 71 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEVVSB0q2E3ebUlEnn:-LhFB7ZEEFVAX971JhgV:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L71)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

It is not necessary, that's a fact but you will get rid of this warnings - it is low hanging fruit :)
Additionally please see that original maintainers of the code use "unsigned int" type for variable with OPTION_CARDINALITY - so consistency in this is some argument to change it
</blockquote></details>

Done.
___
*[benchmarks/bench_storage.c, line 117 at r1](https://reviewable.io/reviews/pmem/pelikan/12#-LhEW8jGAIBPZaoQXhN_:-LhFB8Hi-w72gSJF-kwI:bfgbm3d) ([raw file](https://github.com/pmem/pelikan/blob/a0d62b89d3626ff98d700bbee86fb5cc683bafb6/benchmarks/bench_storage.c#L117)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Actually it is :)
Try to set latency configuration variable to false, compile the project and run ./bench_cuckoo you will hit segmentation fault.
</blockquote></details>

I realized the pointer is not NULL initialized, I fixed that instead :)
___
*[benchmarks/bench_storage.c, line 181 at r2](https://reviewable.io/reviews/pmem/pelikan/12#-LhF8Q8yDerPaMQO89xv:-LhFCDIxA66gEjZOAf1O:b-y18dev) ([raw file](https://github.com/pmem/pelikan/blob/bcc3d55c23f31125919d5ba3a9846358c548664e/benchmarks/bench_storage.c#L181)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> duration_compare
> ```
nit:
Have you consider to rename this function duration_compare_asc or duration_compare_ascending - just to have clear information about order.
</blockquote></details>

comparators in stdlib are a strictly defined thing, and it's up to the algorithm to sort things in ascending or descending order.

**Comment by michalbiesek** [comment]
@nvml-bot
test this please

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/12)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @pbalcer)

___
*[deps/ccommon/include/time/cc_timer.h, line 62 at r3](https://reviewable.io/reviews/pmem/pelikan/12#-LhFR52b6iN6BDduEC9_:-LhFR52b6iN6BDduEC9a:bq9a86n) ([raw file](https://github.com/pmem/pelikan/blob/6329d28095bd79953303047872dad0d308f365a3/deps/ccommon/include/time/cc_timer.h#L62)):*
> ```
>  bool        started;
> ```
I cannot currently check it - but I am pretty sure you must define here  enum duration_type type; ( under OS_DARWIN)

This also apply to duration_start_type function in https://github.com/pmem/pelikan/blob/master/deps/ccommon/src/time/cc_timer_darwin.c

Without it compilation of benchmark will fail under mac os.
___
*[deps/ccommon/include/time/cc_timer.h, line 89 at r3](https://reviewable.io/reviews/pmem/pelikan/12#-LhFSiQ5EfMSn5EEn4r4:-LhFSiQ5EfMSn5EEn4r5:b-hqln9s) ([raw file](https://github.com/pmem/pelikan/blob/5588d8b70cbdc74c9cdd72bc4186ab7f0fbce942/deps/ccommon/include/time/cc_timer.h#L89)):*
> ```objc
> };
> ```

nit:
remove this change please
___
*[deps/ccommon/src/time/cc_timer_linux.c, line 158 at r3](https://reviewable.io/reviews/pmem/pelikan/12#-LhFSuZn3J-AM49E-LhU:-LhFSRHlB0hJtMiASrZC:b-lgwe7l) ([raw file](https://github.com/pmem/pelikan/blob/5588d8b70cbdc74c9cdd72bc4186ab7f0fbce942/deps/ccommon/src/time/cc_timer_linux.c#L158)):*
> ```C
>     _gettime(&now);
>     return now.tv_sec * NSEC_PER_SEC + now.tv_nsec;
> ```

remove this change please

**Review by pbalcer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/12)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[deps/ccommon/include/time/cc_timer.h, line 62 at r3](https://reviewable.io/reviews/pmem/pelikan/12#-LhFR52b6iN6BDduEC9_:-LhFUvcW1dxBtnP1oEka:bfk7dp) ([raw file](https://github.com/pmem/pelikan/blob/6329d28095bd79953303047872dad0d308f365a3/deps/ccommon/include/time/cc_timer.h#L62)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  bool        started;
> ```
I cannot currently check it - but I am pretty sure you must define here  enum duration_type type; ( under OS_DARWIN)

This also apply to duration_start_type function in https://github.com/pmem/pelikan/blob/master/deps/ccommon/src/time/cc_timer_darwin.c

Without it compilation of benchmark will fail under mac os.

</blockquote></details>

I don't see anything that might indicate the these two types must have the same size or definitions. All that matters is that they are defined in the header so that you allocate them statically.
___
*[deps/ccommon/src/time/cc_timer_linux.c, line 158 at r3](https://reviewable.io/reviews/pmem/pelikan/12#-LhFSuZn3J-AM49E-LhU:-LhFV7CB2xeXcTlqxgGq:bvftnxo) ([raw file](https://github.com/pmem/pelikan/blob/5588d8b70cbdc74c9cdd72bc4186ab7f0fbce942/deps/ccommon/src/time/cc_timer_linux.c#L158)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

remove this change please
</blockquote></details>

It's an extraneous empty line after `return`. I think we can safely remove it :P

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/12#-:-LhFWZ4g5Yx_Apaqr7Of:bnfp4nl)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @michalbiesek)

**Pull request merged**
