### PR TITLE
Test assert metrics patch

### PR DESCRIPTION
**Pull request by TomekIdczak97**
Some simple changes in test_assert_metrics function.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/71)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/71)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 156 at r1](https://reviewable.io/reviews/pmem/pelikan/71#-LmnJHjp9zUGQhNcXKnL:-LmnJHjp9zUGQhNcXKnM:bgk2j98) ([raw file](https://github.com/pmem/pelikan/blob/3a2bccb0b90439dcaa6fc0082f0efc5b7cb6d73d/test/storage/slab_pmem/check_slab_pmem.c#L156)):*
> ```
>  char *diff1_buf;
> ```
please do definition an allocation in one line
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 173 at r1](https://reviewable.io/reviews/pmem/pelikan/71#-LmnJNXL64ELfSxlal-C:-LmnJNXL64ELfSxlal-D:b3cf0w6) ([raw file](https://github.com/pmem/pelikan/blob/3a2bccb0b90439dcaa6fc0082f0efc5b7cb6d73d/test/storage/slab_pmem/check_slab_pmem.c#L173)):*
> ```
> strcmp
> ```
cc_strcmp
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 744 at r1](https://reviewable.io/reviews/pmem/pelikan/71#-LmnJOGF7lKlTXDZjhDT:-LmnJOGF7lKlTXDZjhDU:bwebtak) ([raw file](https://github.com/pmem/pelikan/blob/3a2bccb0b90439dcaa6fc0082f0efc5b7cb6d73d/test/storage/slab_pmem/check_slab_pmem.c#L744)):*
> ```C
> END_TEST
> 
> START_TEST(test_freeq)
> ```

this is not related with this PR remove it

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/71)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 156 at r1](https://reviewable.io/reviews/pmem/pelikan/71#-LmnJHjp9zUGQhNcXKnL:-LmnTl829_MJijngYBzA:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3a2bccb0b90439dcaa6fc0082f0efc5b7cb6d73d/test/storage/slab_pmem/check_slab_pmem.c#L156)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  char *diff1_buf;
> ```
please do definition an allocation in one line
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 173 at r1](https://reviewable.io/reviews/pmem/pelikan/71#-LmnJNXL64ELfSxlal-C:-LmnTlf87yrQxwdZ6j6D:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3a2bccb0b90439dcaa6fc0082f0efc5b7cb6d73d/test/storage/slab_pmem/check_slab_pmem.c#L173)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> strcmp
> ```
cc_strcmp
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 744 at r1](https://reviewable.io/reviews/pmem/pelikan/71#-LmnJOGF7lKlTXDZjhDT:-LmnTlzO9lnDmfWoCFdn:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3a2bccb0b90439dcaa6fc0082f0efc5b7cb6d73d/test/storage/slab_pmem/check_slab_pmem.c#L744)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

this is not related with this PR remove it
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/71)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 156 at r2](https://reviewable.io/reviews/pmem/pelikan/71#-LmnXSOm3uNaiA0IoWnk:-LmnXSOm3uNaiA0IoWnl:bemau46) ([raw file](https://github.com/pmem/pelikan/blob/6c92fcf96f9c5e3a8a64b6b6488f147abcebb2c2/test/storage/slab_pmem/check_slab_pmem.c#L156)):*
> ```
>  
> ```
nit: remove space - same apply for all pointers below
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 163 at r2](https://reviewable.io/reviews/pmem/pelikan/71#-LmnXKhH0_hM3pqvvqhF:-LmnXKhH0_hM3pqvvqhG:bkzr3q7) ([raw file](https://github.com/pmem/pelikan/blob/6c92fcf96f9c5e3a8a64b6b6488f147abcebb2c2/test/storage/slab_pmem/check_slab_pmem.c#L163)):*
> ```
> sizeof(metric1_buf)
> ```
METRIC_BUF_LEN
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 166 at r2](https://reviewable.io/reviews/pmem/pelikan/71#-LmnXIlA120r2FtOCiNN:-LmnXIlA120r2FtOCiNO:b-y4u84g) ([raw file](https://github.com/pmem/pelikan/blob/6c92fcf96f9c5e3a8a64b6b6488f147abcebb2c2/test/storage/slab_pmem/check_slab_pmem.c#L166)):*
> ```
> sizeof(metric2_buf)
> ```
METRIC_BUF_LEN
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 169 at r2](https://reviewable.io/reviews/pmem/pelikan/71#-LmnX8Gx47s6gQAfh7aT:-LmnX8GyEs6TwFo9G32b:b-ixf0r1) ([raw file](https://github.com/pmem/pelikan/blob/6c92fcf96f9c5e3a8a64b6b6488f147abcebb2c2/test/storage/slab_pmem/check_slab_pmem.c#L169)):*
> ```
> if(cc_strcmp(metric1_buf, metric2_buf)){
> ```
nit:
if (cc_strcmp(metric1_buf, metric2_buf)) {

space before ( and after )

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/71)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 163 at r2](https://reviewable.io/reviews/pmem/pelikan/71#-LmnXKhH0_hM3pqvvqhF:-LmnZ2xZ-awY6sMWqPya:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/6c92fcf96f9c5e3a8a64b6b6488f147abcebb2c2/test/storage/slab_pmem/check_slab_pmem.c#L163)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> sizeof(metric1_buf)
> ```
METRIC_BUF_LEN
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 166 at r2](https://reviewable.io/reviews/pmem/pelikan/71#-LmnXIlA120r2FtOCiNN:-LmnZ3QFEemYLDXGwtXc:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/6c92fcf96f9c5e3a8a64b6b6488f147abcebb2c2/test/storage/slab_pmem/check_slab_pmem.c#L166)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> sizeof(metric2_buf)
> ```
METRIC_BUF_LEN
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 169 at r2](https://reviewable.io/reviews/pmem/pelikan/71#-LmnX8Gx47s6gQAfh7aT:-LmnZ3y-6gR8_te_KbZR:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/6c92fcf96f9c5e3a8a64b6b6488f147abcebb2c2/test/storage/slab_pmem/check_slab_pmem.c#L169)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if(cc_strcmp(metric1_buf, metric2_buf)){
> ```
nit:
if (cc_strcmp(metric1_buf, metric2_buf)) {

space before ( and after )
</blockquote></details>

Done.

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/71)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 156 at r2](https://reviewable.io/reviews/pmem/pelikan/71#-LmnXSOm3uNaiA0IoWnk:-Lmn_DU1BWoGW8AMhsTq:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/6c92fcf96f9c5e3a8a64b6b6488f147abcebb2c2/test/storage/slab_pmem/check_slab_pmem.c#L156)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  
> ```
nit: remove space - same apply for all pointers below
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/71)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
