### PR TITLE
Basic unit tests for pmem

### PR DESCRIPTION
**Pull request by TomekIdczak97**
Added some basic tests for pmem

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/17)

### CODE REVIEW

**Review by kasiawasiuta — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/17)* status: all files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 489 at r1](https://reviewable.io/reviews/pmem/pelikan/17#-LhLHF7Q6AFPA9LoNml3:-LhLHF7Q6AFPA9LoNml4:b66s66r) ([raw file](https://github.com/pmem/pelikan/blob/8c33bf5596b5a24f571cb318c54e5dd012b11b98/test/storage/slab_pmem/check_slab_pmem.c#L489)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 
>     tcase_add_test(tc_item, test_delete_basic);
>     tcase_add_test(tc_item, test_update_basic);
>     tcase_add_test(tc_item, test_flush_basic);
>     tcase_add_test(tc_item, test_update_basic_after_restart);
> 
> ```
</details>

Please remove uneccesary whitelines

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/17)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @kasiawasiuta and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 143 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HZpl-_obENjVPQAQ:-Li7HZpl-_obENjVPQAR:b-ba1ael) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L143)):*
> ```C
> 
>     test_assert_insert_basic_entry_exists(key);
>     test_reset(0);
> ```

remove your changes from here
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 180 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HbikAs0TT3rE42FC:-Li7HbikAs0TT3rE42FD:b-ba1ael) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L180)):*
> ```C
> 
>     test_assert_insert_large_entry_exists(key);
>     test_reset(0);
> ```

remove your changes from here
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 217 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HcJR7GGSmdLWWRXc:-Li7HcJR7GGSmdLWWRXd:b-ba1ael) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L217)):*
> ```C
>     item_insert(it, &key);
> 
>     test_assert_reserve_backfill_link_exists(it);
> ```

remove your changes from here
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 299 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7Hyoc9ZVmVdHrUzZh:-Li7Hyoc9ZVmVdHrUzZi:b-ba1ael) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L299)):*
> ```C
>     ck_assert_msg(status == ITEM_OK, "item_prepend not OK - return status %d", status);
> 
>     test_reset(0);
> ```

remove your changes from here
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 314 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HlrdE8W-6mEeG3DK:-Li7HlrdE8W-6mEeG3DL:b-uub573) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L314)):*
> ```C
> END_TEST
> ```

nit:
keep one new line as separator not two
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 348 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7Hq5z4ekCry-PLQn4:-Li7Hq5z4ekCry-PLQn5:b-uub573) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L348)):*
> ```C
> }
> END_TEST
> ```

nit:
keep one new line as separator not two
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 384 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HqvC4eRJ1ob2SEyT:-Li7Hh0NBjvExxCB4ZmO:b-uub573) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L384)):*
> ```C
> }
> END_TEST
> ```

nit:
keep one new line as separator not two
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 432 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HrnxClnkCcSX6p75:-Li7HrnxClnkCcSX6p76:b-uub573) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L432)):*
> ```C
> }
> END_TEST
> ```

nit:
keep one new line as separator not two

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/17)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 489 at r1](https://reviewable.io/reviews/pmem/pelikan/17#-LhLHF7Q6AFPA9LoNml3:-LiDOJQj23Fg3lqJW8wl:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/8c33bf5596b5a24f571cb318c54e5dd012b11b98/test/storage/slab_pmem/check_slab_pmem.c#L489)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
> 
>     tcase_add_test(tc_item, test_delete_basic);
>     tcase_add_test(tc_item, test_update_basic);
>     tcase_add_test(tc_item, test_flush_basic);
>     tcase_add_test(tc_item, test_update_basic_after_restart);
> 
> ```
Please remove uneccesary whitelines
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 143 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HZpl-_obENjVPQAQ:-LiDOCxT5u8BGDHgs9Nr:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L143)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

remove your changes from here
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 180 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HbikAs0TT3rE42FC:-LiDODDE7ix9hxnyWFaG:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L180)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

remove your changes from here
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 217 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7HcJR7GGSmdLWWRXc:-LiDODoI7Ja9EylWOe_t:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L217)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

remove your changes from here
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 299 at r2](https://reviewable.io/reviews/pmem/pelikan/17#-Li7Hyoc9ZVmVdHrUzZh:-LiDOEDs1DFhGVx2q5lI:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a21c6f4c60f6164fdcad25ad14727e72979f422b/test/storage/slab_pmem/check_slab_pmem.c#L299)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

remove your changes from here
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/17)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @kasiawasiuta and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 545 at r4](https://reviewable.io/reviews/pmem/pelikan/17#-LiHW7dg3MrdtLLIKCpV:-LiHW7dg3MrdtLLIKCpW:b-sx5l7s) ([raw file](https://github.com/pmem/pelikan/blob/604cfd79d666aa65c7249160ce487a0253a9d4ea/test/storage/slab_pmem/check_slab_pmem.c#L545)):*
> ```C
> END_TEST
> 
> START_TEST(test_delete_basic)
> ```

nit:
Any chance to keep same order of function like in check_slab.c ?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 692 at r4](https://reviewable.io/reviews/pmem/pelikan/17#-LiHX9B9ArDyQlDR_wFe:-LiHX9B9ArDyQlDR_wFf:bia0l4t) ([raw file](https://github.com/pmem/pelikan/blob/604cfd79d666aa65c7249160ce487a0253a9d4ea/test/storage/slab_pmem/check_slab_pmem.c#L692)):*
> ```
> item_update(it, &new_val);
> ```
You should perform item_get after reset
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 723 at r4](https://reviewable.io/reviews/pmem/pelikan/17#-LiHWMFd8xc6wJcsONSd:-LiHWMFd8xc6wJcsONSe:b-sx5l7s) ([raw file](https://github.com/pmem/pelikan/blob/604cfd79d666aa65c7249160ce487a0253a9d4ea/test/storage/slab_pmem/check_slab_pmem.c#L723)):*
> ```C
>     tcase_add_test(tc_item, test_expire_truncated);
>     tcase_add_test(tc_item, test_delete_basic);
>     tcase_add_test(tc_item, test_update_basic);
> ```

nit:
Any chance to keep same order of function like in check_slab.c ?

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/17)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 692 at r4](https://reviewable.io/reviews/pmem/pelikan/17#-LiHX9B9ArDyQlDR_wFe:-LiHtvpa5aVhSM84tJmD:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/604cfd79d666aa65c7249160ce487a0253a9d4ea/test/storage/slab_pmem/check_slab_pmem.c#L692)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> item_update(it, &new_val);
> ```
You should perform item_get after reset
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/17#-:-LiI0WMn06ucsZaJx6qB:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta)

**Pull request merged**
