### PR TITLE
Expiration unit tests for pmem

### PR DESCRIPTION
**Pull request by TomekIdczak97**
Add expiration unit tests for pmem.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/20)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/20)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 95 at r1](https://reviewable.io/reviews/pmem/pelikan/20#-Li7FRe13tFS4_rUD0IW:-Li7FRe13tFS4_rUD0IX:b-2um4aq) ([raw file](https://github.com/pmem/pelikan/blob/ba070c2825147c62d6a0fb18902fb117e818deae/test/storage/slab_pmem/check_slab_pmem.c#L95)):*
> ```
> struct item *it
> ```
You don't need this as parameter in your function.

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/20)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 95 at r1](https://reviewable.io/reviews/pmem/pelikan/20#-Li7FRe13tFS4_rUD0IW:-LiDM7UiEAY_cfgUJrre:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/ba070c2825147c62d6a0fb18902fb117e818deae/test/storage/slab_pmem/check_slab_pmem.c#L95)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct item *it
> ```
You don't need this as parameter in your function.
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/20)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 108 at r2](https://reviewable.io/reviews/pmem/pelikan/20#-LiDiLZB5Aetk8mCg7yk:-LiDiLZB5Aetk8mCg7yl:b403jfj) ([raw file](https://github.com/pmem/pelikan/blob/b9ebb88d13ea2a03b8d32225f6e83be4a6efe6a1/test/storage/slab_pmem/check_slab_pmem.c#L108)):*
> ```C
> }
> 
> static void
> ```

Please be so kind and rebase 
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 109 at r2](https://reviewable.io/reviews/pmem/pelikan/20#-LiDiFiZBlUw2J1ktYzO:-LiDiFiZBlUw2J1ktYzP:b-5mzg8q) ([raw file](https://github.com/pmem/pelikan/blob/b9ebb88d13ea2a03b8d32225f6e83be4a6efe6a1/test/storage/slab_pmem/check_slab_pmem.c#L109)):*
> ```
> int
> ```
proc_time_i

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/20)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 108 at r2](https://reviewable.io/reviews/pmem/pelikan/20#-LiDiLZB5Aetk8mCg7yk:-LiDoRqzAHupVa07w9x3:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b9ebb88d13ea2a03b8d32225f6e83be4a6efe6a1/test/storage/slab_pmem/check_slab_pmem.c#L108)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please be so kind and rebase 
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 109 at r2](https://reviewable.io/reviews/pmem/pelikan/20#-LiDiFiZBlUw2J1ktYzO:-LiDoS5T71wDquCOqkiD:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b9ebb88d13ea2a03b8d32225f6e83be4a6efe6a1/test/storage/slab_pmem/check_slab_pmem.c#L109)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> int
> ```
proc_time_i
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/20#-:-LiDq9dU4TlGwuf3nJKb:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
