### PR TITLE
Add ITT instrumentation

### PR DESCRIPTION
**Pull request by vinser52**
Initial version of VTune instrumentation for cuckoo storage engine

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/7)

### CODE REVIEW

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/7)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @vinser52)

___
*[CMakeLists.txt, line 51 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-Lgki1yz4RQZyz0ayWZc:-Lgki1yz4RQZyz0ayWZd:bjs1hq5) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/CMakeLists.txt#L51)):*
> ```
> Instrument
> ```
nit:
small letter please: "instrument"
___
*[CMakeLists.txt, line 151 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-LgkaA3IDU4g3KH1oBb-:-LgkaA3IDU4g3KH1oBb0:b-8vqtqf) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/CMakeLists.txt#L151)):*
> ```
> pkg_check_modules(ITTNOTIFY REQUIRED ittnotify>=1.0)
> ```
Could you replace it with:
    if(PKG_CONFIG_FOUND)
       pkg_check_modules(ITTNOTIFY REQUIRED ittnotify>=1.0)
    else()
        find_package(ITTNOTIFY REQUIRED 1.0)
  endif()

To check existence of ittnotify package even without PKG_CONFIG
___
*[cmake/config.h.in, line 25 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-Lgkadp0AtQ1AlbQ2NwJ:-Lgkadp0AtQ1AlbQ2NwK:bxetcwt) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/cmake/config.h.in#L25)):*
> ```
> #cmakedefine HAVE_ITT_INSTRUMENTATION
> ```
nit:
Could this be moved below macro #cmakedefine HAVE_STATS
___
*[deps/ccommon/CMakeLists.txt, line 60 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-Lgkhx1O9pIUcAu8o8nA:-Lgkhx1O9pIUcAu8o8nB:b576pg2) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/deps/ccommon/CMakeLists.txt#L60)):*
> ```
> Instrument
> ```
nit:
small letter in the beginning "instrument"
___
*[src/storage/cuckoo/cuckoo.c, line 18 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-LgkhJ81BsnG51iIQFEP:-LgkhJ821HbiVEU5gNqn:b93lq9y) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/src/storage/cuckoo/cuckoo.c#L18)):*
> ```
> __itt_heap_function cuckoo_free
> ```
is this needed ? I am not Vtune expert but I see that this function is only created.
Is free function only apply in case of "__itt_heap_free_begin" or "__itt_heap_free_end".

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/7)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @michalbiesek and @vinser52)

___
*[CMakeLists.txt, line 51 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-Lgki1yz4RQZyz0ayWZc:-Lgl88Ue3Zy5ctCrgOyH:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/CMakeLists.txt#L51)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Instrument
> ```
nit:
small letter please: "instrument"
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 151 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-LgkaA3IDU4g3KH1oBb-:-Lgl87wkB0EpYRGRF6qR:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/CMakeLists.txt#L151)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pkg_check_modules(ITTNOTIFY REQUIRED ittnotify>=1.0)
> ```
Could you replace it with:
    if(PKG_CONFIG_FOUND)
       pkg_check_modules(ITTNOTIFY REQUIRED ittnotify>=1.0)
    else()
        find_package(ITTNOTIFY REQUIRED 1.0)
  endif()

To check existence of ittnotify package even without PKG_CONFIG

</blockquote></details>

Done.
___
*[cmake/config.h.in, line 25 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-Lgkadp0AtQ1AlbQ2NwJ:-Lgl7TbADy1gUIA4_tUV:b-rrfgp3) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/cmake/config.h.in#L25)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #cmakedefine HAVE_ITT_INSTRUMENTATION
> ```
nit:
Could this be moved below macro #cmakedefine HAVE_STATS
</blockquote></details>

I am not sure. From my point of view it is orthogonal features. You may want to profile pelikan with VTune without STATS enabled. 
___
*[src/storage/cuckoo/cuckoo.c, line 18 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-LgkhJ81BsnG51iIQFEP:-Lgl7pw10LDNS7NjermL:b-xdtolo) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/src/storage/cuckoo/cuckoo.c#L18)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> __itt_heap_function cuckoo_free
> ```
is this needed ? I am not Vtune expert but I see that this function is only created.
Is free function only apply in case of "__itt_heap_free_begin" or "__itt_heap_free_end".
</blockquote></details>

Right now it is not used. So, I removed it for now. We can add it in the future if it will be required.

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/7)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[deps/ccommon/CMakeLists.txt, line 60 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-Lgkhx1O9pIUcAu8o8nA:-Lgl9X9H3bw3h8UgntlM:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/deps/ccommon/CMakeLists.txt#L60)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> Instrument
> ```
nit:
small letter in the beginning "instrument"
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/7)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @vinser52)

___
*[CMakeLists.txt, line 154 at r2](https://reviewable.io/reviews/pmem/pelikan/7#-LglpYPWBuFbMaYfdXBg:-LglpYPWBuFbMaYfdXBh:bueer7b) ([raw file](https://github.com/pmem/pelikan/blob/111717d20c5d236324326399c28c02dfb2253870/CMakeLists.txt#L154)):*
> ```
> find_package(ITTNOTIFY REQUIRED 1.0)
> ```
I am not CMake expert but I think this should require separate file where are instruction for cmake to set properly variables and do the job which pkg_check_modules usually do. ( something likehttps://github.com/pmem/pelikan/blob/master/cmake/FindCheck.cmake)

Anyway if you have file for iitnotify to do this job it would be great, but if not let's just use only solution with:
 pkg_check_modules(ITTNOTIFY REQUIRED ittnotify>=1.0).

I am fine with both solutions - so please choose one.
___
*[cmake/config.h.in, line 25 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-Lgkadp0AtQ1AlbQ2NwJ:-LglplQ71R59t97HLDJF:b-c4n8e9) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/cmake/config.h.in#L25)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I am not sure. From my point of view it is orthogonal features. You may want to profile pelikan with VTune without STATS enabled. 
</blockquote></details>

I just want to move this variable in this file. 
#cmakedefine HAVE_ITT_INSTRUMENTATION would be in "HAVE_XXX" section ( like HAVE_BACKTRACE, HAVE_LOGGING etc)  and not in "TARGET_YYY" ( like TARGET_SLIMCACHE, TARGET_TWEMCACHE or TARGET_REDIS".
But it just cosmetics so you could ignore it
___
*[deps/ccommon/config.h.in, line 19 at r2](https://reviewable.io/reviews/pmem/pelikan/7#-LglqV2h59L5GD9Mut7H:-LglqV2h59L5GD9Mut7I:bcy50un) ([raw file](https://github.com/pmem/pelikan/blob/111717d20c5d236324326399c28c02dfb2253870/deps/ccommon/config.h.in#L19)):*
> ```
> #cmakedefine HAVE_LOGGING
> 
> #cmakedefine HAVE_STATS
> ```

Could you please update a commit message:
I think it would be helpful to have a instructions what are requirements for pelikan project to compile correctly with HAVE_ITT_INSTRUMENTATION:
Vtune installed and call amplxe-vars.sh before calling cmake ( the part you share it offline with team members)

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/7)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[CMakeLists.txt, line 154 at r2](https://reviewable.io/reviews/pmem/pelikan/7#-LglpYPWBuFbMaYfdXBg:-Lh-_mZY33edwNpAEVRs:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/111717d20c5d236324326399c28c02dfb2253870/CMakeLists.txt#L154)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> find_package(ITTNOTIFY REQUIRED 1.0)
> ```
I am not CMake expert but I think this should require separate file where are instruction for cmake to set properly variables and do the job which pkg_check_modules usually do. ( something likehttps://github.com/pmem/pelikan/blob/master/cmake/FindCheck.cmake)

Anyway if you have file for iitnotify to do this job it would be great, but if not let's just use only solution with:
 pkg_check_modules(ITTNOTIFY REQUIRED ittnotify>=1.0).

I am fine with both solutions - so please choose one.
</blockquote></details>

Done.
___
*[cmake/config.h.in, line 25 at r1](https://reviewable.io/reviews/pmem/pelikan/7#-Lgkadp0AtQ1AlbQ2NwJ:-Lh-_avpEV-XZ7XKqoRY:b-kih9l6) ([raw file](https://github.com/pmem/pelikan/blob/265b866ca096af7ea96fbd68928e8edfbc2a0186/cmake/config.h.in#L25)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

I just want to move this variable in this file. 
#cmakedefine HAVE_ITT_INSTRUMENTATION would be in "HAVE_XXX" section ( like HAVE_BACKTRACE, HAVE_LOGGING etc)  and not in "TARGET_YYY" ( like TARGET_SLIMCACHE, TARGET_TWEMCACHE or TARGET_REDIS".
But it just cosmetics so you could ignore it
</blockquote></details>

Got it. Done.
___
*[deps/ccommon/config.h.in, line 19 at r2](https://reviewable.io/reviews/pmem/pelikan/7#-LglqV2h59L5GD9Mut7H:-Lh-ajKX6Rvs0mgUTblG:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/111717d20c5d236324326399c28c02dfb2253870/deps/ccommon/config.h.in#L19)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Could you please update a commit message:
I think it would be helpful to have a instructions what are requirements for pelikan project to compile correctly with HAVE_ITT_INSTRUMENTATION:
Vtune installed and call amplxe-vars.sh before calling cmake ( the part you share it offline with team members)
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by michalbiesek** [comment]
@nvml-bot 
 test this please

**Pull request merged**
