### PR TITLE
Add pmem test scenario for ungraceful shutdown

### PR DESCRIPTION
**Pull request by TomekIdczak97**
Adding test checking availability of items after ungraceful shutdown for pmem

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)

### CODE REVIEW

**Comment by kasiawasiuta** [comment]
@pmem-bot-ae 
test this please

**Comment by kasiawasiuta** [comment]
@pmem-bot-ae
test this please

**Comment by kasiawasiuta** [comment]
@pmem-bot-ae
test this please

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @TomekIdczak97)

___
*[test/integration/test_twemcache.py, line 5 at r1](https://reviewable.io/reviews/pmem/pelikan/61#-LlG0Q-Q443qfH2zMesM:-LlG0Q-S4pzXtPJwkbz-:b-7kb4kz) ([raw file](https://github.com/pmem/pelikan/blob/5e39c5d52b95f57abcab7bf746bda8f6746b8713/test/integration/test_twemcache.py#L5)):*
> ```Python
> 
> from os import listdir
> import os
> ```

Decide whether you want to import only 'path',  'remove' and listdir from os or the whole module.
___
*[test/integration/test_twemcache.py, line 15 at r1](https://reviewable.io/reviews/pmem/pelikan/61#-LlG12eRBsSKSacu4IL4:-LlG12eRBsSKSacu4IL5:blr02mr) ([raw file](https://github.com/pmem/pelikan/blob/5e39c5d52b95f57abcab7bf746bda8f6746b8713/test/integration/test_twemcache.py#L15)):*
> ```Python
>         test.load('twemcache/' + fname)
>         suite.addTest(test)
>     for fname in listdir('twemcache'):
> ```

Consider creating a function for this loop with a GenericTest/GenericPmemTest provided as an argument to avoid repeating same code.

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[test/integration/test_twemcache.py, line 5 at r1](https://reviewable.io/reviews/pmem/pelikan/61#-LlG0Q-Q443qfH2zMesM:-LlWlOPKBZRgCt3ZqGDt:bgl9xo0) ([raw file](https://github.com/pmem/pelikan/blob/5e39c5d52b95f57abcab7bf746bda8f6746b8713/test/integration/test_twemcache.py#L5)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Decide whether you want to import only 'path',  'remove' and listdir from os or the whole module.
</blockquote></details>

It can't be done another way.
___
*[test/integration/test_twemcache.py, line 15 at r1](https://reviewable.io/reviews/pmem/pelikan/61#-LlG12eRBsSKSacu4IL4:-LlWlgFA497yTO08UWPt:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/5e39c5d52b95f57abcab7bf746bda8f6746b8713/test/integration/test_twemcache.py#L15)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Consider creating a function for this loop with a GenericTest/GenericPmemTest provided as an argument to avoid repeating same code.
</blockquote></details>

Done.

**Review by llugin — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: all files reviewed, 5 unresolved discussions (waiting on @PatKamin and @TomekIdczak97)

___
*[test/integration/test_twemcache.py, line 8 at r2](https://reviewable.io/reviews/pmem/pelikan/61#-LlfFrVM8ra5vRWtIWCY:-LlfFrVM8ra5vRWtIWCZ:b-2wuzbg) ([raw file](https://github.com/pmem/pelikan/blob/5571f9d12952bc6662499030873b8527aca08ddc/test/integration/test_twemcache.py#L8)):*
> ```Python
> import unittest
> 
> def defineTest(suite, fname, type):
> ```

'type' is a built-in name in python. It's safer not to override built-in names. By convention, you can add '_' suffix ('type_').
___
*[test/integration/twemcache.conf, line 1 at r2](https://reviewable.io/reviews/pmem/pelikan/61#-LlfH_Mc0ymRn2cP2HRW:-LlfH_Mc0ymRn2cP2HRX:bt4fkol) ([raw file](https://github.com/pmem/pelikan/blob/5571f9d12952bc6662499030873b8527aca08ddc/test/integration/twemcache.conf#L1)):*
> ```
> # if slab profile is specified, then the profile wil be explicitly set
> ```

Pls mark new sentences with periods and capital letters.
___
*[test/integration/twemcache.conf, line 4 at r2](https://reviewable.io/reviews/pmem/pelikan/61#-LlfHCpzDkUdAOL1-k-G:-LlfHCpzDkUdAOL1-k-H:b-fxfm2q) ([raw file](https://github.com/pmem/pelikan/blob/5571f9d12952bc6662499030873b8527aca08ddc/test/integration/twemcache.conf#L4)):*
> ```
> # otherwise, slab profile will be generated by using growth factor, slab size,
> # and item min/max size
> # For example, you can specify all item sizes allowed with slab_profile:
> ```

all allowed item sizes?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @llugin, @PatKamin, and @TomekIdczak97)

___
*[test/integration/test_twemcache.py, line 5 at r1](https://reviewable.io/reviews/pmem/pelikan/61#-LlG0Q-Q443qfH2zMesM:-LlfyJ4C0ZqoeYEEQkq0:b1guhu5) ([raw file](https://github.com/pmem/pelikan/blob/5e39c5d52b95f57abcab7bf746bda8f6746b8713/test/integration/test_twemcache.py#L5)):*
<details><summary><i>Previously, TomekIdczak97 wrote…</i></summary><blockquote>

It can't be done another way.
</blockquote></details>

Just use os.listdir

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @llugin and @PatKamin)

___
*[test/integration/test_twemcache.py, line 5 at r1](https://reviewable.io/reviews/pmem/pelikan/61#-LlG0Q-Q443qfH2zMesM:-LlfygvZ4ziMqEs95Mfg:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/5e39c5d52b95f57abcab7bf746bda8f6746b8713/test/integration/test_twemcache.py#L5)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Just use os.listdir
</blockquote></details>

Done.
___
*[test/integration/test_twemcache.py, line 8 at r2](https://reviewable.io/reviews/pmem/pelikan/61#-LlfFrVM8ra5vRWtIWCY:-Llg-Ytf5OGmkFCxhyBL:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/5571f9d12952bc6662499030873b8527aca08ddc/test/integration/test_twemcache.py#L8)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

'type' is a built-in name in python. It's safer not to override built-in names. By convention, you can add '_' suffix ('type_').
</blockquote></details>

Done.
___
*[test/integration/twemcache.conf, line 1 at r2](https://reviewable.io/reviews/pmem/pelikan/61#-LlfH_Mc0ymRn2cP2HRW:-LlfyiBt6HZ9yIVMEr54:b-gpmwxp) ([raw file](https://github.com/pmem/pelikan/blob/5571f9d12952bc6662499030873b8527aca08ddc/test/integration/twemcache.conf#L1)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

Pls mark new sentences with periods and capital letters.
</blockquote></details>

This is config file from examples which can be found in pelikan/config directory.
___
*[test/integration/twemcache.conf, line 4 at r2](https://reviewable.io/reviews/pmem/pelikan/61#-LlfHCpzDkUdAOL1-k-G:-Llfz5tu7Qsx0Wl8yfTu:b-gpmwxp) ([raw file](https://github.com/pmem/pelikan/blob/5571f9d12952bc6662499030873b8527aca08ddc/test/integration/twemcache.conf#L4)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

all allowed item sizes?
</blockquote></details>

This is config file from examples which can be found in pelikan/config directory.

**Review by llugin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @llugin and @TomekIdczak97)

___
*[test/integration/test_twemcache.py, line 8 at r3](https://reviewable.io/reviews/pmem/pelikan/61#-Llg5jWi6-tv5BtdEQPo:-Llg5jWi6-tv5BtdEQPp:b-n4fs4d) ([raw file](https://github.com/pmem/pelikan/blob/b9c5b7cf372869aca647409f364d14874ac38c55/test/integration/test_twemcache.py#L8)):*
> ```Python
> 
> def defineTest(suite, fname, test_type):
>     test = type()
> ```

test_type()

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @llugin)

___
*[test/integration/test_twemcache.py, line 8 at r3](https://reviewable.io/reviews/pmem/pelikan/61#-Llg5jWi6-tv5BtdEQPo:-LlkFUcA8823R0W3NOof:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b9c5b7cf372869aca647409f364d14874ac38c55/test/integration/test_twemcache.py#L8)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

test_type()
</blockquote></details>

Done.

**Review by llugin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @llugin and @TomekIdczak97)

___
*[test/integration/test_twemcache.py, line 14 at r4](https://reviewable.io/reviews/pmem/pelikan/61#-LlketPy2U3cGWkJTIuA:-LlketPy2U3cGWkJTIuB:b-klx9mx) ([raw file](https://github.com/pmem/pelikan/blob/3d3115dcf4448c7989ae0037a372ded85fe10f8c/test/integration/test_twemcache.py#L14)):*
> ```Python
> def twemcache():
>     suite = unittest.TestSuite()
>     for fname in os.listdir('twemcache'):
> ```

What if the 'fname' is a directory?

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @llugin)

___
*[test/integration/test_twemcache.py, line 14 at r4](https://reviewable.io/reviews/pmem/pelikan/61#-LlketPy2U3cGWkJTIuA:-LllBvKU4ZeIihGd5vKm:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3d3115dcf4448c7989ae0037a372ded85fe10f8c/test/integration/test_twemcache.py#L14)):*
<details><summary><i>Previously, llugin wrote…</i></summary><blockquote>

What if the 'fname' is a directory? 
</blockquote></details>

Done.

**Review by llugin — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61#-:-LllY7AW-2P8dYAk4GUS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @llugin and @TomekIdczak97)

___
*[test/integration/test_twemcache.py, line 2 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRf7KUCiB9KIUUCndC:-LnRf7KVDiud6wkvO9rj:bfi5n9u) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L2)):*
> ```Python
> from base import GenericTest
> from base import GenericPmemTest
> ```

Please extend commit message about intention:
- include information about signal that there is no handling SIGTERM signal which is called in python scripts
- include information that your test depend to sequence order
___
*[test/integration/test_twemcache.py, line 6 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRTUkt1yAdfC3K9pZv:-LnRTUku6h68hiwnw4T9:b-nyrl4k) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L6)):*
> ```
> import ConfigParser
> ```
Please check if this work with Python3
___
*[test/integration/test_twemcache.py, line 16 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRSiLB88MH9opTaDq9:-LnRSiLB88MH9opTaDqA:bloa4iy) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L16)):*
> ```
> os.listdir('twemcache'):
> ```
According to https://docs.python.org/2.7/library/os.html#os.listdir "The list is in arbitrary order" so please revert changes related to renaming sequence files and sort it before enter loop
something like sorted(os.listdir('twemcache')) would do the job - do this as separate commit in same PR and in commit message describe the intention of this change
___
*[test/integration/test_twemcache.py, line 27 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRSc886OHLAr9inYWk:-LnRSc886OHLAr9inYWl:bhd5k9s) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L27)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     with open('twemcache.conf') as f:
>         file_content = StringIO.StringIO('[dummy_section]\n' + f.read())
> 
>     config = ConfigParser.ConfigParser()
>     config.readfp(file_content)
>     devpath = config.get('dummy_section','slab_datapool')
> 
>     if os.path.exists(devpath):
> ```
</details>

Extract  this to separate method

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @llugin and @michalbiesek)

___
*[test/integration/test_twemcache.py, line 2 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRf7KUCiB9KIUUCndC:-Lnlmo7ABS1Rsc9ojKMB:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L2)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please extend commit message about intention:
- include information about signal that there is no handling SIGTERM signal which is called in python scripts
- include information that your test depend to sequence order
</blockquote></details>

Done.
___
*[test/integration/test_twemcache.py, line 6 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRTUkt1yAdfC3K9pZv:-Lnlmoa-0Y8n96LYTqlj:bep0mb6) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L6)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> import ConfigParser
> ```
Please check if this work with Python3
</blockquote></details>

It does not.
___
*[test/integration/test_twemcache.py, line 16 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRSiLB88MH9opTaDq9:-LnlmvTD-6E6GVo4Keex:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L16)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> os.listdir('twemcache'):
> ```
According to https://docs.python.org/2.7/library/os.html#os.listdir "The list is in arbitrary order" so please revert changes related to renaming sequence files and sort it before enter loop
something like sorted(os.listdir('twemcache')) would do the job - do this as separate commit in same PR and in commit message describe the intention of this change
</blockquote></details>

Done.
___
*[test/integration/test_twemcache.py, line 27 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRSc886OHLAr9inYWk:-LnlnlGS4CIkwiZFzIVI:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L27)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     with open('twemcache.conf') as f:
>         file_content = StringIO.StringIO('[dummy_section]\n' + f.read())
> 
>     config = ConfigParser.ConfigParser()
>     config.readfp(file_content)
>     devpath = config.get('dummy_section','slab_datapool')
> 
>     if os.path.exists(devpath):
> ```
Extract  this to separate method
</blockquote></details>

Done.

**Review by llugin — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61#-:-LnlqrfhBegTdVn5fOsW:bnfp4nl)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @llugin and @michalbiesek)

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @llugin and @TomekIdczak97)

___
*[test/integration/base.py, line 53 at r7](https://reviewable.io/reviews/pmem/pelikan/61#-Lnm7IwD0Dt1NGGI58QZ:-Lnm7IwD0Dt1NGGI58Q_:b-bid5ej) ([raw file](https://github.com/pmem/pelikan/blob/8efa13f1e1af4fd01d6155b3339fdcdae2697d51/test/integration/base.py#L53)):*
> sequence order of scenarios is needed only if we want to check if test crushes with SIGTERM (as expected)

Change this, you don't need only for graceful shutdown. 
You also need this for ungraceful shutdown - your whole PR depends from order of tests.
___
*[test/integration/test_twemcache.py, line 6 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRTUkt1yAdfC3K9pZv:-LnlozjR7Fedv-yvpVwy:b-mjd9f4) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L6)):*
<details><summary><i>Previously, TomekIdczak97 (tomekidczak) wrote…</i></summary><blockquote>

It does not.
</blockquote></details>

So please do it work. I think code below would work

try:
    import ConfigParser as ConfigParser
except ImportError:
    import configparser as ConfigParser

Similar situation is regarding StringIO - that this would fail on python3
___
*[test/integration/test_twemcache.py, line 25 at r7](https://reviewable.io/reviews/pmem/pelikan/61#-Lnm48Jw1WsFj0P_Vy9F:-Lnm48Jw1WsFj0P_Vy9G:bd93gco) ([raw file](https://github.com/pmem/pelikan/blob/8efa13f1e1af4fd01d6155b3339fdcdae2697d51/test/integration/test_twemcache.py#L25)):*
> ```
> '[dummy_section]\n'
> ```
If this would go upstream repository, please be so kind and add here some comment why you would need to do it - this workaround for missing section

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @llugin and @michalbiesek)

___
*[test/integration/base.py, line 53 at r7](https://reviewable.io/reviews/pmem/pelikan/61#-Lnm7IwD0Dt1NGGI58QZ:-Lnpozyp7CYzP4l9gRBQ:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/8efa13f1e1af4fd01d6155b3339fdcdae2697d51/test/integration/base.py#L53)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> sequence order of scenarios is needed only if we want to check if test crushes with SIGTERM (as expected)

Change this, you don't need only for graceful shutdown. 
You also need this for ungraceful shutdown - your whole PR depends from order of tests.
</blockquote></details>

Done.
___
*[test/integration/test_twemcache.py, line 6 at r6](https://reviewable.io/reviews/pmem/pelikan/61#-LnRTUkt1yAdfC3K9pZv:-Lnpp2hB7hAcD71S5THv:b-ft3m0o) ([raw file](https://github.com/pmem/pelikan/blob/38f581c1f5811baff05804bac17a737ad3f1d974/test/integration/test_twemcache.py#L6)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

So please do it work. I think code below would work

try:
    import ConfigParser as ConfigParser
except ImportError:
    import configparser as ConfigParser

Similar situation is regarding StringIO - that this would fail on python3
</blockquote></details>

Original test also does not work on python3.
___
*[test/integration/test_twemcache.py, line 25 at r7](https://reviewable.io/reviews/pmem/pelikan/61#-Lnm48Jw1WsFj0P_Vy9F:-LnppIn74cDZE_z3SjN0:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/8efa13f1e1af4fd01d6155b3339fdcdae2697d51/test/integration/test_twemcache.py#L25)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> '[dummy_section]\n'
> ```
If this would go upstream repository, please be so kind and add here some comment why you would need to do it - this workaround for missing section

</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @llugin and @TomekIdczak97)

___
*[test/integration/base.py, line 46 at r8](https://reviewable.io/reviews/pmem/pelikan/61#-Lnq6OvbD9aJVP2oyiv_:-Lnq6OvcB5I-BA2Qgov2:b-szt3qu) ([raw file](https://github.com/pmem/pelikan/blob/2b3ffbe8e5c1b7b2aaf2083047d0bc3bb813ee58/test/integration/base.py#L46)):*
> -SIGKILL is used to shutdown server (test/integration/server.py line 52)
> -SIGTERM should crush test

SIGKILL is used to perform ungraceful shutdown of server (self.server.kill())

remove the part: "SIGTERM should crush test"
___
*[test/integration/twemcache.conf, line 7 at r8](https://reviewable.io/reviews/pmem/pelikan/61#-Lnq7Ek021b3bIr0SqsA:-Lnq7Ek021b3bIr0SqsB:b-6a5tqb) ([raw file](https://github.com/pmem/pelikan/blob/2b3ffbe8e5c1b7b2aaf2083047d0bc3bb813ee58/test/integration/twemcache.conf#L7)):*
> ```
> # slab_profile: 1024 2048 4096 8192 16384 32768 65536 131072 262144 524288
> 
> debug_log_level: 4
> ```

nit:
remove params:
debug_log_level
klog_sample
klog_max
slab_evict_opt

The default values are the same as the ones present in this config.
Please remove the comment in the beginning of this script

**Review by TomekIdczak97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @llugin and @michalbiesek)

___
*[test/integration/base.py, line 46 at r8](https://reviewable.io/reviews/pmem/pelikan/61#-Lnq6OvbD9aJVP2oyiv_:-LnqI-oQ8zeHvL0dnK_a:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/2b3ffbe8e5c1b7b2aaf2083047d0bc3bb813ee58/test/integration/base.py#L46)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> -SIGKILL is used to shutdown server (test/integration/server.py line 52)
> -SIGTERM should crush test

SIGKILL is used to perform ungraceful shutdown of server (self.server.kill())

remove the part: "SIGTERM should crush test"
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/61#-:-LnqMRh702rM-RKBiEfn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
