### PR TITLE
Add arguments to use pmem in server config files.

### PR DESCRIPTION
**Pull request by PatKamin**
Add argument for creating twemcache|slimcache configs.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)

### CODE REVIEW

**Comment by pmem-bot-ae** [comment]
Can one of the admins verify this patch?

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @PatKamin)

___
*[scripts/load_testing/generate.sh, line 15 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzE9nJDEJhAA8qvzql:-LjzE9nJDEJhAA8qvzqm:b40l9j9) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/generate.sh#L15)):*
> ```
> pelikan="pelikan_twemcache"
> ```
?
___
*[scripts/load_testing/server_config.py, line 125 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzCMuY2zyusB2zAaHk:-LjzCMuY2zyusB2zAaHl:b-qh8tty) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L125)):*
> ```
> search_text
> ```
nit:
consider other name like prefill_opt or something like that
___
*[scripts/load_testing/server_config.py, line 150 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzBVmOCqgqYosFGxAx:-LjzBVmOCqgqYosFGxAy:b2cegi7) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L150)):*
> ```
> help='a list of pmem mount points'
> ```
nit:
without "a" in description
___
*[scripts/load_testing/server_config.py, line 150 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzCug-BL_rDQSbDN9R:-LjzCug-BL_rDQSbDN9S:bnkgvon) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L150)):*
> ```
> nargs='*'
> ```
Why? Shouldn't this be limited for specific number of arguments?
___
*[scripts/load_testing/server_config.py, line 151 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzBPDYBaUL-h5hvpQG:-LjzBPDYBaUL-h5hvpQH:b7exhxz) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L151)):*
> ```
> a type of engine: twemcache or slimcache
> ```
nit:
without "a" in description

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[scripts/load_testing/server_config.py, line 89 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzUs33CaQi_pDK8mOL:-LjzUs348wDV-3g0Ea60:bgpztxn) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L89)):*
> ```
> slab_datapool_prefault
> ```
question:
No cuckoo_datapool_prefault ?

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @michalbiesek)

___
*[scripts/load_testing/generate.sh, line 15 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzE9nJDEJhAA8qvzql:-Lk-G8TI-RbIH_GLwa50:bx4t0p2) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/generate.sh#L15)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pelikan="pelikan_twemcache"
> ```
?
</blockquote></details>

line 89 allows to remove additional parameter for engine type
___
*[scripts/load_testing/server_config.py, line 89 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzUs33CaQi_pDK8mOL:-Lk-ITp07NVI10sKgXju:b-j2gfd6) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L89)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> slab_datapool_prefault
> ```
question:
No cuckoo_datapool_prefault ?
</blockquote></details>

Added cuckoo_datapool_prefault.
___
*[scripts/load_testing/server_config.py, line 125 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzCMuY2zyusB2zAaHk:-Lk-IZD25U7WD-PMjsjd:b-8to2b0) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L125)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> search_text
> ```
nit:
consider other name like prefill_opt or something like that
</blockquote></details>

Renamed to prefill_opt
___
*[scripts/load_testing/server_config.py, line 150 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzBVmOCqgqYosFGxAx:-Lk-Ib2VEAWXGdWlO3-M:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L150)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> help='a list of pmem mount points'
> ```
nit:
without "a" in description
</blockquote></details>

Done.
___
*[scripts/load_testing/server_config.py, line 150 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzCug-BL_rDQSbDN9R:-Lk-IjCM0IzlL7CKZ0PY:b2enpqc) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L150)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> nargs='*'
> ```
Why? Shouldn't this be limited for specific number of arguments?
</blockquote></details>

It allows to use one or more mount points.
___
*[scripts/load_testing/server_config.py, line 151 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzBPDYBaUL-h5hvpQG:-Lk-IhXn7Carjux51Eas:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L151)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> a type of engine: twemcache or slimcache
> ```
nit:
without "a" in description
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @PatKamin)

___
*[scripts/load_testing/generate.sh, line 15 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzE9nJDEJhAA8qvzql:-Lk2huJn3_8ta_i3nzLP:b-9j8c9g) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/generate.sh#L15)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

line 89 allows to remove additional parameter for engine type
</blockquote></details>

Yes, what I missed here is information about default engine which is generated in case you did not pass -p param, but this is a matter of extending the usage section - please feel free to ignore this comment :)
___
*[scripts/load_testing/generate.sh, line 28 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2fClf9zBhf8QlYnki:-Lk2fClgEd_3EWOIZCCs:br6k3le) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/generate.sh#L28)):*
> ```
> e:
> ```
remove
___
*[scripts/load_testing/generate.sh, line 40 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2fZFz0_1dHAqdkr9P:-Lk2fZFz0_1dHAqdkr9Q:b-45n5ag) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/generate.sh#L40)):*
> ```
> ($OPTARG)
> ```
brackets are needed here ?
___
*[scripts/load_testing/generate.sh, line 89 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2gjonAUbOhSXdN8Fq:-Lk2gjoo-DHqtkLWCRGo:b-egcf0d) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/generate.sh#L89)):*
> ```
> if [[ $($pelikan --help | grep -ic slimcache) > 0 ]] ; then engine="slimcache" ; else engine="twemcache" ; fi
> ```
IMHO this should be done on python layer ( python_server_config)
I am note sure about how this will extend time of script generation, but it would simplify solution here with passing the param
___
*[scripts/load_testing/server_config.py, line 150 at r1](https://reviewable.io/reviews/pmem/pelikan/43#-LjzCug-BL_rDQSbDN9R:-Lk2jhNm0tYJ84Ez2bFg:b-80s02j) ([raw file](https://github.com/pmem/pelikan/blob/5a2110e5d39744e6d36f76a5a05f39a85b8e756e/scripts/load_testing/server_config.py#L150)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

It allows to use one or more mount points.
</blockquote></details>

If it allows for more parameters then showhelp() in generate.sh must be updated - I assumed that there is a limit ( 2 pmem paths) for it regarding description there
___
*[scripts/load_testing/server_config.py, line 37 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk-JZgL6U2sRXF1y7FX:-Lk-JZgL6U2sRXF1y7FY:b-xobdzx) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/server_config.py#L37)):*
> ```
> '{engine}-{server_port}.config'.format(server_port=server_port, engine=engine)
> ```
nit:
Could you please change order of format arguments, would be easier for read to me
___
*[scripts/load_testing/server_config.py, line 111 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2fzUbDvm4CcZYdwE-:-Lk2fzUbDvm4CcZYdwE0:b-dyja81) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/server_config.py#L111)):*
> ```
> format(server_port=PELIKAN_SERVER_PORT+i, engine=engine))
> ```
nit:
Could you please change order of format arguments, would be easier for read to me
___
*[scripts/load_testing/server_config.py, line 138 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2g4IKBY0_wlSUsn0-:-Lk2g4IKBY0_wlSUsn00:b-outl6d) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/server_config.py#L138)):*
> ```
> engine=engine, prefill_opt=prefill_opt))
> ```
nit:
Could you please change order of format arguments, would be easier for read to me

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @PatKamin)

___
*[scripts/load_testing/generate.sh, line 89 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2l_hkAjBbJXcRdJI0:-Lk2l_hkAjBbJXcRdJI1:bs5onoo) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/generate.sh#L89)):*
> ```
> if [[ $($pelikan --help | grep -ic slimcache) > 0 ]] ; then engine="slimcache" ; else engine="twemcache" ; fi
> ```
I would not assume that if there aren't slimchache phrases it must be twemcache.
I think that there should be check for slimcache and for twemcache. In other words detect the situation when neither were found (slimcache or twemcache)

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @michalbiesek)

___
*[scripts/load_testing/generate.sh, line 28 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2fClf9zBhf8QlYnki:-Lk34F6m-SRy_2kIPaPc:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/generate.sh#L28)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> e:
> ```
remove
</blockquote></details>

Done.
___
*[scripts/load_testing/generate.sh, line 40 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2fZFz0_1dHAqdkr9P:-Lk34YFBD7kH6c9Qy4zW:b-pwxe1) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/generate.sh#L40)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ($OPTARG)
> ```
brackets are needed here ?
</blockquote></details>

Yes, they save `$OPTARG` as a list rather than a string. It allows one to easily check the number of pmem paths provided with len() method.
___
*[scripts/load_testing/generate.sh, line 89 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2gjonAUbOhSXdN8Fq:-Lk4IlsZ6ZiyBRNwwPC_:b-slwelu) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/generate.sh#L89)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if [[ $($pelikan --help | grep -ic slimcache) > 0 ]] ; then engine="slimcache" ; else engine="twemcache" ; fi
> ```
IMHO this should be done on python layer ( python_server_config)
I am note sure about how this will extend time of script generation, but it would simplify solution here with passing the param
</blockquote></details>

Moved to python layer.
___
*[scripts/load_testing/generate.sh, line 89 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2l_hkAjBbJXcRdJI0:-Lk4Io9a654VhnjsW6tw:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/generate.sh#L89)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if [[ $($pelikan --help | grep -ic slimcache) > 0 ]] ; then engine="slimcache" ; else engine="twemcache" ; fi
> ```
I would not assume that if there aren't slimchache phrases it must be twemcache.
I think that there should be check for slimcache and for twemcache. In other words detect the situation when neither were found (slimcache or twemcache)
</blockquote></details>

Done.
___
*[scripts/load_testing/server_config.py, line 37 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk-JZgL6U2sRXF1y7FX:-Lk35qQh3IRdLcd5mqx4:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/server_config.py#L37)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> '{engine}-{server_port}.config'.format(server_port=server_port, engine=engine)
> ```
nit:
Could you please change order of format arguments, would be easier for read to me
</blockquote></details>

Done.
___
*[scripts/load_testing/server_config.py, line 111 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2fzUbDvm4CcZYdwE-:-Lk36N9GC-YClR6PBrOz:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/server_config.py#L111)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> format(server_port=PELIKAN_SERVER_PORT+i, engine=engine))
> ```
nit:
Could you please change order of format arguments, would be easier for read to me
</blockquote></details>

Done.
___
*[scripts/load_testing/server_config.py, line 138 at r2](https://reviewable.io/reviews/pmem/pelikan/43#-Lk2g4IKBY0_wlSUsn0-:-Lk36B6YCg1gSnJ9lKCP:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a7d76088d5afa678e4c1c9437cdef3101faf5ec1/scripts/load_testing/server_config.py#L138)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> engine=engine, prefill_opt=prefill_opt))
> ```
nit:
Could you please change order of format arguments, would be easier for read to me
</blockquote></details>

Done.

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: all files reviewed, 2 unresolved discussions (waiting on @PatKamin)

___
*[scripts/load_testing/server_config.py, line 31 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4PH-6EJt3QHVBcAPn:-Lk4PH-6EJt3QHVBcAPo:b6l7coo) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L31)):*
> ```
> (vsize + KSIZE + PELIKAN_ITEM_OVERHEAD)))
> ```
nit:
but could you define item_size before nkey and here refer to item_size ?
___
*[scripts/load_testing/server_config.py, line 95 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4O-qn5TQ3THA2Riqb:-Lk4O-qoBSB-GV7ao9hl:b-2kmd3g) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L95)):*
> ```
> stats_log_file: log/{engine}-{server_port}.stats
> ```
nit:
Correct me if I am wrong but I think you don't need to pass engine here - this is only valid for twemcache so IMHO it could be leave as it is stats_log_file: log/twemcache-{server_port}.stats

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: all files reviewed, 6 unresolved discussions (waiting on @PatKamin)

___
*[scripts/load_testing/server_config.py, line 67 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4UCsf38auj6ooEGBg:-Lk4UCsf38auj6ooEGBh:bb34o58) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L67)):*
> ```Python
> request_poolsize: 16384
> response_poolsize: 32768
> ```

nit:
As we spoke offline consider adding a comment to separate common and engine part
___
*[scripts/load_testing/server_config.py, line 101 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4ToB95rqslzYzcDK2:-Lk4ToB95rqslzYzcDK3:bnuvw2q) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L101)):*
> ```
> {datapool_param}: {pmem_path}
> ```
nit:
Consider move here whole logic of parsing e.g the part:
    # else use twemcache settings
    else:
        datapool_param = "slab_datapool"
And similary for slimcache
___
*[scripts/load_testing/server_config.py, line 102 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4TgVeDqGFWMBFTj3T:-Lk4TgVeDqGFWMBFTj3U:b-yri374) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L102)):*
> ```
> "".format(pmem_path=pmem_paths[i%len(pmem_paths)], datapool_param=datapool_param)
> ```
as we spoke offline here should be path to file not directory /mnt/pmem/temp_file not /mnt/pmem
___
*[scripts/load_testing/server_config.py, line 104 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4U101Ed6nAI5-8V7Y:-Lk4U101Ed6nAI5-8V7Z:b-hoz28a) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L104)):*
> ```
> pmem_path_str
> ```
I think the logic of multiple pmem_path is missing here

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[scripts/load_testing/server_config.py, line 31 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4PH-6EJt3QHVBcAPn:-Lk4VJW572qAWMcZaaYl:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L31)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> (vsize + KSIZE + PELIKAN_ITEM_OVERHEAD)))
> ```
nit:
but could you define item_size before nkey and here refer to item_size ?
</blockquote></details>

Done.
___
*[scripts/load_testing/server_config.py, line 95 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4O-qn5TQ3THA2Riqb:-Lk4ZBmzBBRbVHUr0apm:b-wymc4r) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L95)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> stats_log_file: log/{engine}-{server_port}.stats
> ```
nit:
Correct me if I am wrong but I think you don't need to pass engine here - this is only valid for twemcache so IMHO it could be leave as it is stats_log_file: log/twemcache-{server_port}.stats
</blockquote></details>

Correct. Done.
___
*[scripts/load_testing/server_config.py, line 101 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4ToB95rqslzYzcDK2:-Lk4aQRCET38jFUuXYAy:b-b10gxw) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L101)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> {datapool_param}: {pmem_path}
> ```
nit:
Consider move here whole logic of parsing e.g the part:
    # else use twemcache settings
    else:
        datapool_param = "slab_datapool"
And similary for slimcache
</blockquote></details>

I split twemcache|slimcache logic and pmem logic because then you can use configs for slimcache or twemcache with or without the pmem usage.
___
*[scripts/load_testing/server_config.py, line 102 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4TgVeDqGFWMBFTj3T:-Lk4antE21f1mmxJRLTk:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L102)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> "".format(pmem_path=pmem_paths[i%len(pmem_paths)], datapool_param=datapool_param)
> ```
as we spoke offline here should be path to file not directory /mnt/pmem/temp_file not /mnt/pmem
</blockquote></details>

Done.
___
*[scripts/load_testing/server_config.py, line 104 at r3](https://reviewable.io/reviews/pmem/pelikan/43#-Lk4U101Ed6nAI5-8V7Y:-Lk4asIi6UuPIUNORKSG:bdwmw2g) ([raw file](https://github.com/pmem/pelikan/blob/a2db5ebc0d9f79108b83d77eec5510f8ce79e3fa/scripts/load_testing/server_config.py#L104)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pmem_path_str
> ```
I think the logic of multiple pmem_path is missing here 
</blockquote></details>

It's not. Different config files get different pmem_paths: `pmem_paths[i%len(pmem_paths)]`

**Review by michalbiesek — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @PatKamin)

___
*[scripts/load_testing/server_config.py, line 111 at r4](https://reviewable.io/reviews/pmem/pelikan/43#-Lk7lkU41QV0zHQsaHmC:-Lk7lkU41QV0zHQsaHmD:b-5h3n1c) ([raw file](https://github.com/pmem/pelikan/blob/f43c7f9324bf23e5ef86341093b3000b4e0b7e31/scripts/load_testing/server_config.py#L111)):*
> ```
> pmem_paths
> ```
nit:
In this function you only need information about number of mounting devices.
You don't need the actual address of devices - so this could be simplified by calling this function with len(pmem_paths) as param.
___
*[scripts/load_testing/server_config.py, line 120 at r4](https://reviewable.io/reviews/pmem/pelikan/43#-Lk7mtNM0sKtGr0CtlUA:-Lk7mtNM0sKtGr0CtlUB:b-4xyniz) ([raw file](https://github.com/pmem/pelikan/blob/f43c7f9324bf23e5ef86341093b3000b4e0b7e31/scripts/load_testing/server_config.py#L120)):*
> ```
> len(pmem_paths)))
> ```
Nit:
Imho you could create a variable before open file like numa_node_calc and assign to it in form 
numa_node_calc = pmem_devices if pmem_devices != 0 else 2

It would simplify this if else part.
Feel free to use other variable names the code above is just to present concept
___
*[scripts/load_testing/server_config.py, line 123 at r4](https://reviewable.io/reviews/pmem/pelikan/43#-Lk7mYqw5_w4uzZ1I6dS:-Lk7mYqw5_w4uzZ1I6dT:b-xicieh) ([raw file](https://github.com/pmem/pelikan/blob/f43c7f9324bf23e5ef86341093b3000b4e0b7e31/scripts/load_testing/server_config.py#L123)):*
> ```
> numa_node=0))
> ```
Question:
Here you are changing the previous behavior. I mean now if you don't pass any pmem device you assign to numa node zero, before it was i%2

**Review by PatKamin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @michalbiesek)

___
*[scripts/load_testing/server_config.py, line 111 at r4](https://reviewable.io/reviews/pmem/pelikan/43#-Lk7lkU41QV0zHQsaHmC:-Lk7zcAf-beRlP2-xYwg:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/f43c7f9324bf23e5ef86341093b3000b4e0b7e31/scripts/load_testing/server_config.py#L111)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> pmem_paths
> ```
nit:
In this function you only need information about number of mounting devices.
You don't need the actual address of devices - so this could be simplified by calling this function with len(pmem_paths) as param.

</blockquote></details>

Done.
___
*[scripts/load_testing/server_config.py, line 120 at r4](https://reviewable.io/reviews/pmem/pelikan/43#-Lk7mtNM0sKtGr0CtlUA:-Lk7zav48VJN6pUH7I85:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/f43c7f9324bf23e5ef86341093b3000b4e0b7e31/scripts/load_testing/server_config.py#L120)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> len(pmem_paths)))
> ```
Nit:
Imho you could create a variable before open file like numa_node_calc and assign to it in form 
numa_node_calc = pmem_devices if pmem_devices != 0 else 2

It would simplify this if else part.
Feel free to use other variable names the code above is just to present concept
</blockquote></details>

Done.
___
*[scripts/load_testing/server_config.py, line 123 at r4](https://reviewable.io/reviews/pmem/pelikan/43#-Lk7mYqw5_w4uzZ1I6dS:-Lk7x_bmD6fXKqZhR4vt:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/f43c7f9324bf23e5ef86341093b3000b4e0b7e31/scripts/load_testing/server_config.py#L123)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> numa_node=0))
> ```
Question:
Here you are changing the previous behavior. I mean now if you don't pass any pmem device you assign to numa node zero, before it was i%2
</blockquote></details>

Done.

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43#-:-Lk8FVnl-xGTPvYMfama:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by michalbiesek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/43#-:-Lk8ImjYA7j5A3rxBOFC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
